<?php
return [
    'categories' => [
        "accounting" => "Accounting",
        "art_and_design" => "Art and Design",
        "business" => "Business",
        "computing_and_it" => "Computing and IT",
        "economics" => "Economics",
        "engineering" => "Engineering",
        "english_language" => "English Language",
        "exam_preparation_english_course" => "Exam Preparation English Course",
        "humanities-and-social-science" => "Humanities and Social Science",
        "law" => "Law",
        "life-science" => "Life Science",
        "management" => "Management",
        "marketing" => "Marketing",
        "mathematics-and-statistics" => "Mathematics and Statistics",
        "media" => "Media",
        "medical" => "Medical",
        "other-courses" => "Other Courses",
        "science" => "Science",
        "senior-secondary-high-school" => "Senior Secondary High School",
        "social-science" => "Social Science",
        "education" => "Education",
        "cultural-studies" => "Cultural Studies",
        "sports-and-nutrition" => "Sports and Nutrition",
        "applied-science" => "Applied Science",
    ],
    'categories_limit' => 10,
    'destination' => [
        "united_kingdom" =>'United Kingdom',
        "new_zealand" =>'New Zealand',
        "united_state_of_america" =>'United State of America',
        "europe" => 'Europe',
        "australia" =>'Australia',
        "malaysia" =>'Malaysia',
        "china" =>'China',
        "germany" =>'Germany',
        "canada" =>'Canada',
        "ireland" =>'Ireland',
        "france" =>'France',
        "hungary" =>'Hungary',
        "cyprus" =>'Cyprus',
        "united_arab_emirates" =>'United Arab Emirates',
        "grenada" =>'Grenada'
    ],
    'levels' => [
        "a_level" =>'A Level',
        "english_language_preparation" =>'English Language Preparation',
        "foundation" =>'Foundation',
        "high_school" =>'High School',
        "international_year_one" =>'International year one',
        "postgraduate" =>'Postgraduate',
        "postgraduate_research" =>'Postgraduate Research',
        "pre-dba" =>'Pre-DBA',
        "pre-masters" =>'Pre-Masters',
        "undergraduate" =>'Undergraduate',
        "certificate" =>'Certificate',
        "diploma" =>'Diploma',
    ]
];
